---
- name: Restore backup
  ansible.builtin.command: "{{ RESTORE_SCRIPT }} {{ BACKUP_LOCATION }}_{{ privx_version }}"

- name: Run postinstall script
  ansible.builtin.command: "{{ POST_INSTALL_SCRIPT }}"
