---
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com


  # Install a collection from Ansible Galaxy.
  - name: community.postgresql
    version: ">=2.4.3"
    source: https://galaxy.ansible.com
