---
- name: Create directory
  file:
    path: "{{ BACKUP_LOCATION }}"
    state: directory

- name: Copy and uncompress backup
  unarchive:
    src: "/tmp/{{ ansible_play_hosts_all[0] }}{{ BACKUP_FILE }}"
    dest: "{{ BACKUP_LOCATION }}"
  notify:
    - Restore backup
    - Run postinstall script
