---
- name: Detect if keyvault already exist
  ansible.builtin.stat:
    path: /opt/privx/keyvault
  register: keyvault

- name: Generate privx configuration script using template
  ansible.builtin.template:
    src: config.j2
    dest: "{{ CONFIGURATION_SCRIPT }}"
    mode: 0700
  when: not keyvault.stat.exists

- name: Execute privx configuration script
  ansible.builtin.command: "{{ CONFIGURATION_SCRIPT }}"
  when: not keyvault.stat.exists

- name: Delete privx configuraiton script
  ansible.builtin.file:
    path: "{{ CONFIGURATION_SCRIPT }}"
    state: absent
