---
- name: Detect if keyvault already exist
  stat:
    path: /opt/privx/keyvault
  register: keyvault

- name: Generate privx configuration script using template
  template:
    src: config.j2
    dest: "{{ CONFIGURATION_SCRIPT }}"
    mode: 0700
  when: keyvault.stat.exists == False

- name: Execute privx configuration script
  shell: "{{ CONFIGURATION_SCRIPT }}"
  args:
    executable: /bin/bash
  when: keyvault.stat.exists == False

- name: Delete privx configuraiton script
  file:
    path: "{{ CONFIGURATION_SCRIPT }}"
    state: absent