---
- name: Install postgresql repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install postgresql
  yum:
    name: ['{{ POSTGRESQL_PACKAGE }}-server', 'python-psycopg2', 'python2-cryptography']
    state: installed

- name: Check database already initialized
  stat:
    path: "{{ PGSQL_PATH }}/PG_VERSION"
  register: init_status

- name: Initialize database
  shell: "/usr/pgsql-{{ PGSQL_VERSION }}/bin/postgresql-{{ PGSQL_VERSION }}-setup initdb"
  when: init_status.stat.exists == False
  notify:

- name: Start and enable postgresql service
  service:
    name: "{{ POSTGRESQL_SERVICE }}"
    state: started
    enabled: yes

- name: Create database user
  become_user: postgres
  become: yes
  no_log: True
  postgresql_user:
    name: "{{ PRIVX_DATABASE_USERNAME }}"
    password: "{{ PRIVX_DATABASE_PASSWORD }}"
    role_attr_flags: CREATEDB

- name: Install openssl
  yum:
    name: openssl
    state: present

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ PGSQL_PATH }}/server.key"
    owner: postgres
    group: postgres
    mode: 0600

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ PGSQL_PATH }}/server.csr"
    privatekey_path: "{{ PGSQL_PATH }}/server.key"
    common_name: "{{ ansible_fqdn }}"
    owner: postgres
    group: postgres
    mode: 0600

- name: Generate an OpenSSL certificate
  openssl_certificate:
    path: "{{ PGSQL_PATH }}/server.crt"
    privatekey_path: "{{ PGSQL_PATH }}/server.key"
    csr_path: "{{ PGSQL_PATH }}/server.csr"
    provider: selfsigned
    owner: postgres
    group: postgres
    mode: 0644

- name: update listen_addresses
  lineinfile:
    path: "{{ POSTGRESQL_CONFIG }}"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - { regex: "^#listen_addresses", line: "listen_addresses = \'*\'" }
    - { regex: "^max_connections = 100", line: "max_connections = 1000" }
    - { regex: "^#ssl = off", line: "ssl = on" }
    - { regex: "#ssl_cert_file", line: "ssl_cert_file = \'server.crt\'"}
    - { regex: "#ssl_key_file", line: "ssl_key_file = \'server.key\'"}

- name: Grant access from privx ip
  postgresql_pg_hba:
    dest: "{{ PG_HBA_CONFIG }}"
    contype: host
    source: "{{ item }}"
  with_inventory_hostnames:
    - privx
  notify:
    - Restart postgresql service
