---
- name: Create backup
  ansible.builtin.command: "{{ BACKUP_SCRIPT }}"
  when: ansible_play_hosts_all|length  > 1

- name: Find backup
  ansible.builtin.find:
    paths: /var/backups/privx
    file_type: directory
  register: backups

- name: Get latest backup
  ansible.builtin.set_fact:
    latest_backup: "{{ backups.files | sort(attribute='mtime') | last }}"

- name: Compress backup directory
  community.general.archive:
    path:
      - "{{ latest_backup['path'] }}/*"
    dest: "{{ BACKUP_FILE }}"
    mode: "0644"

- name: Fetch backup
  ansible.builtin.fetch:
    src: "{{ BACKUP_FILE }}"
    dest: /tmp
