# This is a basic workflow to help you get started with Actions

name: Ansible code validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
      with:
        targets: "*.yml"
        override-deps: |
          ansible==2.15.11
          ansible-lint==24.7.0
        args: ""

